
version: '2.2'

services:
  mysqldb:
    build: ./patientinfo/scripts
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=groot
      - MYSQL_DATABASE=mediscreen_mysql_db
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    volumes:
      - mysql_db:/var/lib/mysql/

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=mediscreen_mongo
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mroot
    ports:
      - "27018:27017"
    volumes:
      - mongo_db:/var/lib/mongo

  patient_info:
    depends_on:
      mysqldb:
        condition: service_healthy
    build: ./patientinfo
    restart: on-failure
    ports:
      - "8081:8081"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  adminer:
     image: adminer
     restart: always
     ports:
        - "8080:8080"

volumes:
  mysql_db:
  mongo_db: