
version: '2.2'

services:
  mysqldb:
    build: ./patientinfo/scripts
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=groot
      - MYSQL_DATABASE=mediscreen_mysql_db
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    volumes:
      - db:/data/mysql

  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    build: ./patientinfo
    restart: on-failure
    ports:
      - "8081:8081"

    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  adminer:
     image: adminer
     restart: always
     ports:
        - "8080:8080"

volumes:
  db: